/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConfigFile =
    | {
          /**
           * The user may hard-code the JSON Schema for their version of the config.
           */
          $schema?: string | null;
          /**
           * A specific directory to output all artifacts to. When enabling this the babel plugin needs `artifactDirectory` set as well.
           */
          artifactDirectory?: string | null;
          /**
           * Name of the command that runs the relay compiler
           */
          codegenCommand?: string | null;
          /**
           * A map from GraphQL error name to import path, example: {"name:: "MyErrorName", "path": "../src/MyError"}
           */
          customErrorType?: {
              name: string;
              path: string;
              [k: string]: unknown;
          } | null;
          /**
           * A map from GraphQL scalar types to a custom JS type, example: { "Url": "String" } { "Url": {"name:: "MyURL", "path": "../src/MyUrlTypes"} }
           */
          customScalarTypes?: {
              [k: string]:
                  | string
                  | {
                        name: string;
                        path: string;
                        [k: string]: unknown;
                    };
          };
          /**
           * This option enables emitting es modules artifacts.
           */
          eagerEsModules?: boolean;
          enumModuleSuffix?: ForFlowTypeGeneration;
          /**
           * Directories to ignore under src default: ['** /node_modules/**', '** /__mocks__/**', '** /__generated__/**'],
           */
          excludes?: string[];
          /**
           * EXPERIMENTAL: If your environment is configured to handles errors out of band, either via a network layer which discards responses with errors, or via enabling strict error handling in the runtime, you can enable this flag to have Relay generate non-null types for fields which are marked as semantically non-null in the schema.
           *
           * Currently semantically non-null fields must be specified in your schema using the `@semanticNonNull` directive as specified in: https://github.com/apollographql/specs/pull/42
           */
          experimentalEmitSemanticNullabilityTypes?: boolean;
          featureFlags?: {
              actor_change_support?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * @required with an action of THROW is read-time feature that is not compatible with our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
               */
              allow_required_in_mutation_response?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Allow non-nullable return types from resolvers.
               */
              allow_resolver_non_nullable_return_type?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Relay Resolvers are a read-time feature that are not actually handled in our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
               */
              allow_resolvers_in_mutation_response?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Print queries in compact form
               */
              compact_query_text?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Disable validation of the `edgeTypeName` argument on `@prependNode` and `@appendNode`.
               */
              disable_edge_type_name_validation_on_declerative_connection_directives?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Mirror of `enable_resolver_normalization_ast` excludes resolver metadata from reader ast
               */
              disable_resolver_reader_ast?: boolean;
              /**
               * Disable validating the composite schema (server, client schema extensions, Relay Resolvers) after its built.
               */
              disable_schema_validation?: boolean;
              enable_3d_branch_arg_generation?: boolean;
              enable_catch_directive_transform?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Enable support for the experimental `@alias` directive on fragment spreads.
               */
              enable_fragment_aliases?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Add support for parsing and transforming variable definitions on fragment definitions and arguments on fragment spreads.
               */
              enable_fragment_argument_transform?: boolean;
              /**
               * Allow relay resolvers to extend the Mutation type
               */
              enable_relay_resolver_mutations?: boolean;
              enable_relay_resolver_transform?: boolean;
              /**
               * Fully build the normalization AST for Resolvers
               */
              enable_resolver_normalization_ast?: boolean;
              /**
               * Perform strict validations when custom scalar types are used
               */
              enable_strict_custom_scalars?: boolean;
              /**
               * Enforce that you must add `@alias` to a fragment if it may not match, due to type mismatch or `@skip`/`@include`
               */
              enforce_fragment_alias_where_ambiguous?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * For now, this also disallows fragments with variable definitions This also makes @module to opt in using @no_inline internally NOTE that the presence of a fragment in this list only controls whether a fragment is *allowed* to use @no_inline: whether the fragment is inlined or not depends on whether it actually uses that directive.
               */
              no_inline?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Feature flag to prefer `fetch_MyType()` generatior over `node()` query generator in @refetchable transform
               */
              prefer_fetchable_in_refetch_queries?: boolean;
              relay_resolver_enable_interface_output_type?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              skip_printing_nulls?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Enable generation of text artifacts used to generate full query strings later.
               */
              text_artifacts?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
          } | null;
          /**
           * We may generate some content in the artifacts that's stripped in production if __DEV__ variable is set This config option is here to define the name of that special variable
           */
          isDevVariableName?: string | null;
          /**
           * Formatting style for generated files.
           */
          jsModuleFormat?: "commonjs" | "haste";
          /**
           * The desired output language, "flow" or "typescript".
           */
          language: "javascript" | "typescript" | "flow";
          /**
           * Configuration for @module
           */
          moduleImportConfig?: {
              /**
               * Defines the custom import statement to be generated on the `ModuleImport` node in ASTs, used for dynamically loading components at runtime.
               */
              dynamicModuleProvider?:
                  | (
                        | {
                              mode: "JSResource";
                              [k: string]: unknown;
                          }
                        | {
                              mode: "Custom";
                              statement: string;
                              [k: string]: unknown;
                          }
                    )
                  | null;
              /**
               * Defines the surface upon which @module is enabled.
               */
              surface?: ("resolvers" | "all") | null;
          };
          /**
           * This option controls whether or not a catch-all entry is added to enum type definitions for values that may be added in the future. Enabling this means you will have to update your application whenever the GraphQL server schema adds new enum values to prevent it from breaking.
           */
          noFutureProofEnums?: boolean;
          /**
           * Opt out of source control checks/integration.
           */
          noSourceControl?: boolean | null;
          optionalInputFields?: ForFlowTypeGeneration1;
          /**
           * Query Persist Configuration It contains URL and addition parameters that will be included with the request (think API_KEY, APP_ID, etc...)
           */
          persistConfig?:
              | (
                    | {
                          concurrency?: number | null;
                          /**
                           * Additional headers to send
                           */
                          headers?: {
                              [k: string]: string;
                          };
                          includeQueryText?: boolean;
                          /**
                           * The document will be in a POST parameter `text`. This map can contain additional parameters to send.
                           */
                          params?: {
                              [k: string]: string;
                          };
                          /**
                           * URL to send a POST request to to persist.
                           */
                          url: string;
                      }
                    | {
                          algorithm?: "MD5" | "SHA1" | "SHA256";
                          file: string;
                          include_query_text?: boolean;
                      }
                )
              | null;
          /**
           * Require all GraphQL scalar types mapping to be defined, will throw if a GraphQL scalar type doesn't have a JS type
           */
          requireCustomScalarTypes?: boolean;
          /**
           * Configuration for resolvers_schema_module generation
           */
          resolversSchemaModule?: {
              applyToNormalizationAst?: boolean;
              path?: string;
          } | null;
          /**
           * Path to schema.graphql
           */
          schema?: string;
          /**
           * Extra configuration for the schema itself.
           */
          schemaConfig?: {
              /**
               * Configuration where Relay should expect some fields in the schema.
               */
              connectionInterface?: {
                  cursor: string;
                  edges: string;
                  endCursor: string;
                  hasNextPage: string;
                  hasPreviousPage: string;
                  node: string;
                  pageInfo: string;
                  startCursor: string;
              };
              /**
               * Configuration where Relay should expect some fields in the schema.
               */
              deferStreamInterface?: {
                  /**
                   * Wrapper struct for clarity rather than having StringKey everywhere.
                   */
                  deferName: string;
                  ifArg: string;
                  initialCountArg: string;
                  labelArg: string;
                  /**
                   * Wrapper struct for clarity rather than having StringKey everywhere.
                   */
                  streamName: string;
                  useCustomizedBatchArg: string;
              };
              /**
               * The name of the `id` field that exists on the `Node` interface.
               */
              nodeInterfaceIdField?: string;
              /**
               * The name of the variable expected by the `node` query.
               */
              nodeInterfaceIdVariableName?: string;
              /**
               * Configuration of Relay's validation for `id` fields outside of the `Node` interface.
               */
              nonNodeIdFields?: {
                  /**
                   * A map of parent type names to allowed type names for fields named `id`
                   */
                  allowedIdTypes?: {
                      [k: string]: string;
                  };
              } | null;
              /**
               * The name of the directive indicating fields that cannot be selected
               */
              unselectableDirectiveName?: string;
              [k: string]: unknown;
          };
          /**
           * List of directories with schema extensions.
           */
          schemaExtensions?: string[];
          /**
           * Root directory of application code
           */
          src?: string;
          /**
           * Added in 13.1.1 to customize Final/Compat mode in the single project config file Removed in 14.0.0
           */
          typegenPhase?: {
              [k: string]: unknown;
          };
          /**
           * Keep the previous compiler behavior by outputting an union of the raw type and null, and not the **correct** behavior of an union with the raw type, null and undefined.
           */
          typescriptExcludeUndefinedFromNullableUnion?: boolean;
          useImportTypeSyntax?: ForTypescriptTypeGeneration;
      }
    | {
          /**
           * The user may hard-code the JSON Schema for their version of the config.
           */
          $schema?: string | null;
          codegenCommand?: string | null;
          /**
           * Glob patterns that should not be part of the sources even if they are in the source set directories.
           */
          excludes?: string[];
          featureFlags?: {
              actor_change_support?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * @required with an action of THROW is read-time feature that is not compatible with our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
               */
              allow_required_in_mutation_response?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Allow non-nullable return types from resolvers.
               */
              allow_resolver_non_nullable_return_type?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Relay Resolvers are a read-time feature that are not actually handled in our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
               */
              allow_resolvers_in_mutation_response?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Print queries in compact form
               */
              compact_query_text?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Disable validation of the `edgeTypeName` argument on `@prependNode` and `@appendNode`.
               */
              disable_edge_type_name_validation_on_declerative_connection_directives?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Mirror of `enable_resolver_normalization_ast` excludes resolver metadata from reader ast
               */
              disable_resolver_reader_ast?: boolean;
              /**
               * Disable validating the composite schema (server, client schema extensions, Relay Resolvers) after its built.
               */
              disable_schema_validation?: boolean;
              enable_3d_branch_arg_generation?: boolean;
              enable_catch_directive_transform?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Enable support for the experimental `@alias` directive on fragment spreads.
               */
              enable_fragment_aliases?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Add support for parsing and transforming variable definitions on fragment definitions and arguments on fragment spreads.
               */
              enable_fragment_argument_transform?: boolean;
              /**
               * Allow relay resolvers to extend the Mutation type
               */
              enable_relay_resolver_mutations?: boolean;
              enable_relay_resolver_transform?: boolean;
              /**
               * Fully build the normalization AST for Resolvers
               */
              enable_resolver_normalization_ast?: boolean;
              /**
               * Perform strict validations when custom scalar types are used
               */
              enable_strict_custom_scalars?: boolean;
              /**
               * Enforce that you must add `@alias` to a fragment if it may not match, due to type mismatch or `@skip`/`@include`
               */
              enforce_fragment_alias_where_ambiguous?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * For now, this also disallows fragments with variable definitions This also makes @module to opt in using @no_inline internally NOTE that the presence of a fragment in this list only controls whether a fragment is *allowed* to use @no_inline: whether the fragment is inlined or not depends on whether it actually uses that directive.
               */
              no_inline?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Feature flag to prefer `fetch_MyType()` generatior over `node()` query generator in @refetchable transform
               */
              prefer_fetchable_in_refetch_queries?: boolean;
              relay_resolver_enable_interface_output_type?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              skip_printing_nulls?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
              /**
               * Enable generation of text artifacts used to generate full query strings later.
               */
              text_artifacts?:
                  | {
                        kind: "disabled";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "enabled";
                        [k: string]: unknown;
                    }
                  | {
                        allowlist: string[];
                        kind: "limited";
                        [k: string]: unknown;
                    }
                  | {
                        kind: "rollout";
                        /**
                         * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                         */
                        rollout: number | null;
                        [k: string]: unknown;
                    };
          };
          /**
           * Similar to sources but not affected by excludes.
           */
          generatedSources?: {
              /**
               * Set of project names.
               */
              [k: string]: (null | string)[];
          };
          header?: string[];
          /**
           * Then name of the global __DEV__ variable to use in generated artifacts
           */
          isDevVariableName?: string | null;
          /**
           * Optional name for this config, might be used for logging or custom extra artifact generator code.
           */
          name?: string | null;
          /**
           * Opt out of source control checks/integration.
           */
          noSourceControl?: boolean | null;
          /**
           * Configuration of projects to compile.
           */
          projects: {
              [k: string]: {
                  /**
                   * If a base project is set, the documents of that project can be referenced, but won't produce output artifacts. Extensions from the base project will be added as well and the schema of the base project should be a subset of the schema of this project.
                   */
                  base?: (null | string) | null;
                  codegenCommand?: string | null;
                  /**
                   * A map from GraphQL error name to import path, example: {"name:: "MyErrorName", "path": "../src/MyError"}
                   */
                  customErrorType?: {
                      name: string;
                      path: string;
                      [k: string]: unknown;
                  } | null;
                  /**
                   * A map from GraphQL scalar types to a custom JS type, example: { "Url": "String" } { "Url": {"name:: "MyURL", "path": "../src/MyUrlTypes"} }
                   */
                  customScalarTypes?: {
                      [k: string]:
                          | string
                          | {
                                name: string;
                                path: string;
                                [k: string]: unknown;
                            };
                  };
                  /**
                   * Configuration for all diagnostic reporting in the compiler
                   */
                  diagnosticReportConfig?: {
                      /**
                       * Threshold for diagnostics to be critical to the compiler's execution. All diagnostic with severities at and below this level will cause the compiler to fatally exit.
                       */
                      criticalLevel: "error" | "warning" | "info" | "hint";
                      [k: string]: unknown;
                  };
                  /**
                   * This option enables emitting es modules artifacts.
                   */
                  eagerEsModules?: boolean;
                  enumModuleSuffix?: ForFlowTypeGeneration2;
                  /**
                   * EXPERIMENTAL: If your environment is configured to handles errors out of band, either via a network layer which discards responses with errors, or via enabling strict error handling in the runtime, you can enable this flag to have Relay generate non-null types for fields which are marked as semantically non-null in the schema.
                   *
                   * Currently semantically non-null fields must be specified in your schema using the `@semanticNonNull` directive as specified in: https://github.com/apollographql/specs/pull/42
                   */
                  experimentalEmitSemanticNullabilityTypes?: boolean;
                  /**
                   * A placeholder for allowing extra information in the config file
                   */
                  extra?: {
                      [k: string]: unknown;
                  };
                  /**
                   * Some projects may need to generate extra artifacts. For those, we may need to provide an additional directory to put them. By default the will use `output` *if available
                   */
                  extraArtifactsOutput?: string | null;
                  featureFlags?: {
                      actor_change_support?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * @required with an action of THROW is read-time feature that is not compatible with our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
                       */
                      allow_required_in_mutation_response?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Allow non-nullable return types from resolvers.
                       */
                      allow_resolver_non_nullable_return_type?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Relay Resolvers are a read-time feature that are not actually handled in our mutation APIs. We are in the process of removing any existing examples, but this flag is part of a process of removing any existing examples.
                       */
                      allow_resolvers_in_mutation_response?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Print queries in compact form
                       */
                      compact_query_text?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Disable validation of the `edgeTypeName` argument on `@prependNode` and `@appendNode`.
                       */
                      disable_edge_type_name_validation_on_declerative_connection_directives?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Mirror of `enable_resolver_normalization_ast` excludes resolver metadata from reader ast
                       */
                      disable_resolver_reader_ast?: boolean;
                      /**
                       * Disable validating the composite schema (server, client schema extensions, Relay Resolvers) after its built.
                       */
                      disable_schema_validation?: boolean;
                      enable_3d_branch_arg_generation?: boolean;
                      enable_catch_directive_transform?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Enable support for the experimental `@alias` directive on fragment spreads.
                       */
                      enable_fragment_aliases?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Add support for parsing and transforming variable definitions on fragment definitions and arguments on fragment spreads.
                       */
                      enable_fragment_argument_transform?: boolean;
                      /**
                       * Allow relay resolvers to extend the Mutation type
                       */
                      enable_relay_resolver_mutations?: boolean;
                      enable_relay_resolver_transform?: boolean;
                      /**
                       * Fully build the normalization AST for Resolvers
                       */
                      enable_resolver_normalization_ast?: boolean;
                      /**
                       * Perform strict validations when custom scalar types are used
                       */
                      enable_strict_custom_scalars?: boolean;
                      /**
                       * Enforce that you must add `@alias` to a fragment if it may not match, due to type mismatch or `@skip`/`@include`
                       */
                      enforce_fragment_alias_where_ambiguous?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * For now, this also disallows fragments with variable definitions This also makes @module to opt in using @no_inline internally NOTE that the presence of a fragment in this list only controls whether a fragment is *allowed* to use @no_inline: whether the fragment is inlined or not depends on whether it actually uses that directive.
                       */
                      no_inline?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Feature flag to prefer `fetch_MyType()` generatior over `node()` query generator in @refetchable transform
                       */
                      prefer_fetchable_in_refetch_queries?: boolean;
                      relay_resolver_enable_interface_output_type?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      skip_printing_nulls?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                      /**
                       * Enable generation of text artifacts used to generate full query strings later.
                       */
                      text_artifacts?:
                          | {
                                kind: "disabled";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "enabled";
                                [k: string]: unknown;
                            }
                          | {
                                allowlist: string[];
                                kind: "limited";
                                [k: string]: unknown;
                            }
                          | {
                                kind: "rollout";
                                /**
                                 * A utility to enable gradual rollout of large codegen changes. Can be constructed as the Default which passes or a percentage between 0 and 100.
                                 */
                                rollout: number | null;
                                [k: string]: unknown;
                            };
                  } | null;
                  /**
                   * Formatting style for generated files.
                   */
                  jsModuleFormat?: "commonjs" | "haste";
                  /**
                   * The desired output language, "flow" or "typescript".
                   */
                  language: "javascript" | "typescript" | "flow";
                  /**
                   * Configuration for @module.
                   */
                  moduleImportConfig?: {
                      /**
                       * Defines the custom import statement to be generated on the `ModuleImport` node in ASTs, used for dynamically loading components at runtime.
                       */
                      dynamicModuleProvider?:
                          | (
                                | {
                                      mode: "JSResource";
                                      [k: string]: unknown;
                                  }
                                | {
                                      mode: "Custom";
                                      statement: string;
                                      [k: string]: unknown;
                                  }
                            )
                          | null;
                      /**
                       * Defines the surface upon which @module is enabled.
                       */
                      surface?: ("resolvers" | "all") | null;
                  };
                  /**
                   * This option controls whether or not a catch-all entry is added to enum type definitions for values that may be added in the future. Enabling this means you will have to update your application whenever the GraphQL server schema adds new enum values to prevent it from breaking.
                   */
                  noFutureProofEnums?: boolean;
                  optionalInputFields?: ForFlowTypeGeneration3;
                  /**
                   * A project without an output directory will put the generated files in a __generated__ directory next to the input file. All files in these directories should be generated by the Relay compiler, so that the compiler can cleanup extra files.
                   */
                  output?: string | null;
                  /**
                   * If this option is set, the compiler will persist queries using this config.
                   */
                  persist?:
                      | (
                            | {
                                  concurrency?: number | null;
                                  /**
                                   * Additional headers to send
                                   */
                                  headers?: {
                                      [k: string]: string;
                                  };
                                  includeQueryText?: boolean;
                                  /**
                                   * The document will be in a POST parameter `text`. This map can contain additional parameters to send.
                                   */
                                  params?: {
                                      [k: string]: string;
                                  };
                                  /**
                                   * URL to send a POST request to to persist.
                                   */
                                  url: string;
                              }
                            | {
                                  algorithm?: "MD5" | "SHA1" | "SHA256";
                                  file: string;
                                  include_query_text?: boolean;
                              }
                        )
                      | null;
                  /**
                   * Require all GraphQL scalar types mapping to be defined, will throw if a GraphQL scalar type doesn't have a JS type
                   */
                  requireCustomScalarTypes?: boolean;
                  /**
                   * Configuration for resolvers_schema_module generation
                   */
                  resolversSchemaModule?: {
                      applyToNormalizationAst?: boolean;
                      path?: string;
                  } | null;
                  /**
                   * A generic rollout state for larger codegen changes. The default is to pass, otherwise it should be a number between 0 and 100 as a percentage.
                   */
                  rollout?: number | null;
                  /**
                   * Path to the schema.graphql or a directory containing a schema broken up in multiple *.graphql files. Exactly 1 of these options needs to be defined.
                   */
                  schema?: string | null;
                  schemaConfig?: {
                      /**
                       * Configuration where Relay should expect some fields in the schema.
                       */
                      connectionInterface?: {
                          cursor: string;
                          edges: string;
                          endCursor: string;
                          hasNextPage: string;
                          hasPreviousPage: string;
                          node: string;
                          pageInfo: string;
                          startCursor: string;
                      };
                      /**
                       * Configuration where Relay should expect some fields in the schema.
                       */
                      deferStreamInterface?: {
                          /**
                           * Wrapper struct for clarity rather than having StringKey everywhere.
                           */
                          deferName: string;
                          ifArg: string;
                          initialCountArg: string;
                          labelArg: string;
                          /**
                           * Wrapper struct for clarity rather than having StringKey everywhere.
                           */
                          streamName: string;
                          useCustomizedBatchArg: string;
                      };
                      /**
                       * The name of the `id` field that exists on the `Node` interface.
                       */
                      nodeInterfaceIdField?: string;
                      /**
                       * The name of the variable expected by the `node` query.
                       */
                      nodeInterfaceIdVariableName?: string;
                      /**
                       * Configuration of Relay's validation for `id` fields outside of the `Node` interface.
                       */
                      nonNodeIdFields?: {
                          /**
                           * A map of parent type names to allowed type names for fields named `id`
                           */
                          allowedIdTypes?: {
                              [k: string]: string;
                          };
                      } | null;
                      /**
                       * The name of the directive indicating fields that cannot be selected
                       */
                      unselectableDirectiveName?: string;
                      [k: string]: unknown;
                  };
                  schemaDir?: string | null;
                  /**
                   * Directory containing *.graphql files with schema extensions.
                   */
                  schemaExtensions?: string[];
                  /**
                   * If `output` is provided and `shard_output` is `true`, shard the files by putting them under `{output_dir}/{source_relative_path}`
                   */
                  shardOutput?: boolean;
                  /**
                   * Regex to match and strip parts of the `source_relative_path`
                   */
                  shardStripRegex?: string | null;
                  /**
                   * Optional regex to restrict @relay_test_operation to directories matching this regex. Defaults to no limitations.
                   */
                  testPathRegex?: string | null;
                  /**
                   * Keep the previous compiler behavior by outputting an union of the raw type and null, and not the **correct** behavior of an union with the raw type, null and undefined.
                   */
                  typescriptExcludeUndefinedFromNullableUnion?: boolean;
                  useImportTypeSyntax?: ForTypescriptTypeGeneration1;
                  /**
                   * Generates a `// @relayVariables name1 name2` header in generated operation files
                   */
                  variableNamesComment?: boolean;
              };
          };
          /**
           * Root directory relative to the config file. Defaults to the directory where the config is located.
           */
          root?: string | null;
          /**
           * Watchman saved state config.
           */
          savedStateConfig?: {
              mergebase?: string | null;
              "mergebase-with"?: string | null;
              /**
               * Holds extended clock data that includes source control aware query metadata. <https://facebook.github.io/watchman/docs/scm-query.html>
               */
              "saved-state"?: {
                  "commit-id"?: string | null;
                  config?: unknown;
                  storage?: string | null;
                  [k: string]: unknown;
              } | null;
              [k: string]: unknown;
          } | null;
          /**
           * A mapping from directory paths (relative to the root) to a source set. If a path is a subdirectory of another path, the more specific path wins.
           */
          sources: {
              [k: string]: (null | string) | (null | string)[];
          };
      };
/**
 * When set, enum values are imported from a module with this suffix. For example, an enum Foo and this property set to ".test" would be imported from "Foo.test". Note: an empty string is allowed and different from not setting the value, in the example above it would just import from "Foo".
 */
export type ForFlowTypeGeneration = string | null;
/**
 * When set, generated input types will have the listed fields optional even if the schema defines them as required.
 */
export type ForFlowTypeGeneration1 = string[];
/**
 * Whether to use the `import type` syntax introduced in Typescript version 3.8. This will prevent warnings from `importsNotUsedAsValues`.
 */
export type ForTypescriptTypeGeneration = boolean;
/**
 * When set, enum values are imported from a module with this suffix. For example, an enum Foo and this property set to ".test" would be imported from "Foo.test". Note: an empty string is allowed and different from not setting the value, in the example above it would just import from "Foo".
 */
export type ForFlowTypeGeneration2 = string | null;
/**
 * When set, generated input types will have the listed fields optional even if the schema defines them as required.
 */
export type ForFlowTypeGeneration3 = string[];
/**
 * Whether to use the `import type` syntax introduced in Typescript version 3.8. This will prevent warnings from `importsNotUsedAsValues`.
 */
export type ForTypescriptTypeGeneration1 = boolean;
